### ISSUE TITLE
TTrss 1.12 - unread count unstyled

### ISSUE THREAD

**Issue by elleggi** [DarkPreacher/tt-rss-theme-paper#1]
Hi,
after the update to TTRSS 1.12 the unread feeds count is not styled anymore and there are a few other positioning problems (Actions dropdown slides under something else).
Wish I could be of more help but I just really appreciate your theme. 
Crossbrowser and OS problem.

**Comment by DarkPreacher** [comment]
Hi.
Sorry for a huge delay, resolved now, please update to latest version.

**Comment by elleggi** [comment]
Thank you!!! sorry for my delay :dancer:
